// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: reference.proto

package protobuf

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ComponentUnitReference with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ComponentUnitReference) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ComponentUnitReference with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ComponentUnitReferenceMultiError, or nil if none found.
func (m *ComponentUnitReference) ValidateAll() error {
	return m.validate(true)
}

func (m *ComponentUnitReference) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ComponentUnitId

	// no validation rules for ComponentUnitCode

	// no validation rules for DisplayNameLang

	if len(errors) > 0 {
		return ComponentUnitReferenceMultiError(errors)
	}

	return nil
}

// ComponentUnitReferenceMultiError is an error wrapping multiple validation
// errors returned by ComponentUnitReference.ValidateAll() if the designated
// constraints aren't met.
type ComponentUnitReferenceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ComponentUnitReferenceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ComponentUnitReferenceMultiError) AllErrors() []error { return m }

// ComponentUnitReferenceValidationError is the validation error returned by
// ComponentUnitReference.Validate if the designated constraints aren't met.
type ComponentUnitReferenceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ComponentUnitReferenceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ComponentUnitReferenceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ComponentUnitReferenceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ComponentUnitReferenceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ComponentUnitReferenceValidationError) ErrorName() string {
	return "ComponentUnitReferenceValidationError"
}

// Error satisfies the builtin error interface
func (e ComponentUnitReferenceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sComponentUnitReference.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ComponentUnitReferenceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ComponentUnitReferenceValidationError{}

// Validate checks the field values on StaffReference with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StaffReference) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StaffReference with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StaffReferenceMultiError,
// or nil if none found.
func (m *StaffReference) ValidateAll() error {
	return m.validate(true)
}

func (m *StaffReference) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for StaffId

	// no validation rules for StaffCode

	// no validation rules for DisplayNameLang

	if len(errors) > 0 {
		return StaffReferenceMultiError(errors)
	}

	return nil
}

// StaffReferenceMultiError is an error wrapping multiple validation errors
// returned by StaffReference.ValidateAll() if the designated constraints
// aren't met.
type StaffReferenceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StaffReferenceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StaffReferenceMultiError) AllErrors() []error { return m }

// StaffReferenceValidationError is the validation error returned by
// StaffReference.Validate if the designated constraints aren't met.
type StaffReferenceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StaffReferenceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StaffReferenceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StaffReferenceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StaffReferenceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StaffReferenceValidationError) ErrorName() string { return "StaffReferenceValidationError" }

// Error satisfies the builtin error interface
func (e StaffReferenceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStaffReference.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StaffReferenceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StaffReferenceValidationError{}

// Validate checks the field values on UserReference with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserReference) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserReference with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserReferenceMultiError, or
// nil if none found.
func (m *UserReference) ValidateAll() error {
	return m.validate(true)
}

func (m *UserReference) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Email

	// no validation rules for DisplayName

	if len(errors) > 0 {
		return UserReferenceMultiError(errors)
	}

	return nil
}

// UserReferenceMultiError is an error wrapping multiple validation errors
// returned by UserReference.ValidateAll() if the designated constraints
// aren't met.
type UserReferenceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserReferenceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserReferenceMultiError) AllErrors() []error { return m }

// UserReferenceValidationError is the validation error returned by
// UserReference.Validate if the designated constraints aren't met.
type UserReferenceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserReferenceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserReferenceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserReferenceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserReferenceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserReferenceValidationError) ErrorName() string { return "UserReferenceValidationError" }

// Error satisfies the builtin error interface
func (e UserReferenceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserReference.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserReferenceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserReferenceValidationError{}
